// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://npmyrsqofetvbyqiyums.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5wbXlyc3FvZmV0dmJ5cWl5dW1zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1Njk2NjcsImV4cCI6MjA3MjE0NTY2N30.-0qJixxUnqdrpzw0UvSLxE-VanAPrXXPnpKqov_AiNQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});